### ISSUE TITLE
DY!Nevin missing initial burst attack and skill levels

### ISSUE THREAD

**Issue by SteelGram** [SapiensAnatis/Dawnshard#159]
[Found by Green Gobliño Gamer#8175, description based on their report]
**Describe the bug**
DY!Nevin missing initial burst attack and skill levels when acquired

**On branch**
master

**To Reproduce**
Literally just get him somehow

**Expected behavior**
Defaults respected

**Additional context**
Can't really reproduce the skill level thing, it's not unlocked by default either according to our data or the wiki. The burst attack is a very real and reproducable bug though.

**Comment by SapiensAnatis** [comment]
Should have been fixed in #257
