### ISSUE TITLE
Mana circles should deduct materials

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#246]
Currently mana circles don't check or deduct any materials. The mechanism by which the materials are calculated seems unclear, with several masterasset tables possibly involved:

 - ManaMaterial
    - Appears to be a listing of orbs/scales for each element
 - ManaPieceElement
    - Potentially references quantities of items from ManaMaterial 
 - ManaPieceMaterial
    - Potentially contains 'nonstandard' materials for particular circles

**Comment by LukeFZ** [comment]
fixed by #284
