### ISSUE TITLE
Rupie mine upgrade softlock

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#247]
A player became softlocked after /fort/upgrade_at_once errored upgrading a rupie mine.

This lead to them having a rupie mine at level 1 which had the BuildStartDate and BuildEndDate fields populated. This didn't seem invalid at a glance but resetting these to unix timestamp 0 resolved the issue.

![image](https://github.com/SapiensAnatis/Dawnshard/assets/5047192/f271d076-98a2-42c7-8bc2-d45e25d59e33)

Further investigation needed such as exact reproduction steps/data and ADB logs.

**Comment by LukeFZ** [comment]
fixed by #270
