### ISSUE TITLE
T3 event materials unavailable in Accursed Archives and Dream Big Under the Big Top

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#507]
**Describe the bug**
Tier 3 event materials (Colorful Bouquet / Divulgent Lenses) don't drop from challenge battles in the compendium versions of 'Accursed Archives' and 'Dream Big Under the Big Top'

**Expected behavior**
These materials should be available from challenge battles

**Additional context**
This is because in `EventDropService` we subtract the quest's `VariationType` from `VariationTypes.Hard` as a means of limiting T3 drops to challenge battles:

```csharp
// T2 and T3 currency are only used for redeeming shop items, and can appear commonly from Challenge Battle quests.
if (type == DungeonTypes.Wave)
{
    // T3 only drops from Challenge Battle quests
    int t3Quantity = GenerateDropAmount(
        10 * record.wave * ((variation - VariationTypes.Hard) / 2d) * buildDropMultiplier
    );
    yield return new Entity(evt.ViewEntityType3, evt.ViewEntityId3, t3Quantity);
}
```
If a drop with <0 quantity is yielded it will not be awarded.

This works for newer events, but these two events (and possibly others) have all of their challenge battles set to `VariationTypes.Normal` so no quests are eligible for T3 drops.

A proposed fix would be to change the `(variation - VariationTypes.Hard) / 2d` logic to a `GetIsEligibleForT3()` call or similar which can implement a special case of logic for these two events and any others that may be affected. We should ideally remove any dependency on `VariationType` even for quantity due to this discrepancy so that some events aren't harder to grind than others.

**Comment by SidMalladi** [comment]
@SapiensAnatis Hi Jay, can I please be assigned to this issue?

I need a PR merged into an open-source code as part of my assignment for a class, so I'll work on this quickly.

**Comment by SapiensAnatis** [comment]
Looking at the VariationType of wave quests (DungeonType 6) we see there's quite a range between events:

```sql
SELECT t._Text as EventName, q._Id as QuestId, q._VariationType as QuestVariationType FROM EventData e
JOIN QuestData q on e._Id = q._Gid
JOIN TextLabel t on t._Id = e._Name
WHERE e._IsMemoryEvent = 1
AND q._DungeonType = 6
```


EventName | QuestId | QuestVariationType
-- | -- | --
Flames of Reflection | 208160501 | 3
Flames of Reflection | 208160502 | 4
The Miracle of Dragonyule | 208170501 | 1
The Miracle of Dragonyule | 208170502 | 4
A Wish to the Winds | 208180501 | 1
A Wish to the Winds | 208180502 | 4
Dream Big Under the Big Top | 208200501 | 1
Dream Big Under the Big Top | 208200502 | 1
The Hunt for Harmony | 208220501 | 3
The Hunt for Harmony | 208220502 | 4
Trick or Treasure! | 208260501 | 1
Trick or Treasure! | 208260502 | 4
A Crescendo of Courage | 208290501 | 3
A Crescendo of Courage | 208290502 | 4
The Accursed Archives | 208310501 | 1
The Accursed Archives | 208310502 | 1
Agents of the Goddess | 208390501 | 3
Agents of the Goddess | 208390502 | 4
A Dash of Disaster | 208410501 | 3
A Dash of Disaster | 208410502 | 4
Rhythmic Resolutions | 208420501 | 3
Rhythmic Resolutions | 208420502 | 4
The Phantom's Ransom | 208430501 | 3
The Phantom's Ransom | 208430502 | 4
Divine Deception | 208440501 | 3
Divine Deception | 208440502 | 4
Toll of the Deep | 208450501 | 3
Toll of the Deep | 208450502 | 4
The Clockwork Heart | 208460501 | 3
The Clockwork Heart | 208460502 | 4

**Comment by SapiensAnatis** [comment]
We could either use the quest ID mod 10 to work out which is harder or use the difficulty which is consistently 7000 or 12000.
