### ISSUE TITLE
Add campaign skip button

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#525]
**Context**
In the original game there was a campaign skip button which would progress you to the end of chapter 10. It is available after doing a small amount of story to finish the interactive tutorial.

It used to progress your player level and halidom, and grant you some material rewards.

If you did not skip, it used to grant you hustle hammers + materials equivalent to the fort level ups skipping would have granted you.

**The feature request**
This button should be implemented in Dawnshard. We should also implement the reward after Ch.10 for both skipping and not skipping.

**Implementation details**
- The button kicks you to the title screen after pressing it rather than trying to encode the vast amount of data in `update_data_list`
- The main campaign quests can be identified by having a `_Gid` in the `QuestData` asset of `100XX` where XX is the chapter number.
- Unsure about how to identify main campaign stories.
- See packet capture here: https://dragalia-api-docs.readthedocs.io/en/latest/dragalia/story_skip_skip.html

**Comment by jaredstrong89** [comment]
I have begun work on this.

**Comment by jaredstrong89** [comment]
Implementation questions:

1. Do we want to skip the hard and very hard quests?
2. Do we know the details of which buildings to level up? And to what levels?

**Comment by SapiensAnatis** [comment]
1. No, I think it’s just normal as it’s intended to skip past doing story to unlock other parts of the game. Hard/Very Hard is only done to unlock resources. 2. See below linkWiki page: https://dragalialost.wiki/w/Beginner%27s_Guide#The_Story_Skip_OptionSent from my iPhoneOn 24 Apr 2024, at 04:30, jelq ***@***.***> wrote:﻿
Implementation questions:

Do we want to skip the hard and very hard quests?
Do we know the details of which buildings to level up? And to what levels?

**Comment by jaredstrong89** [comment]
I wish I saw this earlier! I manually tested the correct amount of exp already! 🤣

Thanks much!

**Comment by SapiensAnatis** [comment]
@jaredstrong89 Thanks for your PR for the initial issue. Unless I missed something, I don't think it includes the Chapter 10 reward for not skipping. However, I think this can be done in a separate pull request -- would you be happy to contribute that as well?

**Comment by jaredstrong89** [comment]
Yes, I can look into it after making adjustments to the first PR.

**Comment by SapiensAnatis** [comment]
> Yes, I can look into it after making adjustments to the first PR.

@jaredstrong89 I've opened #787 to cover the chapter 10 reward. Let me know if you'd like me to assign it to you :)

**Comment by jaredstrong89** [comment]
Yes, I will take it. I have done some preliminary testing on that one.
