### ISSUE TITLE
Notte’s training regimen softlock

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#54]
**Describe the bug**
A soft lock can occur when notte tries to introduce you to the Royal Regimen

**On branch**
live (develop) on 24/12/2022

**To Reproduce**
Unknown, this didn’t happen in testing but the person reporting the bug closed the app in between completing the tutorial and restarting

**Expected behavior**
You should be able to open the royal regimen menu and proceed with gameplay

**Additional context**
ViewerId = 3 (savefile since cleared)
TutorialStatus  = 10302
TutorialFlag = 0

**Comment by LukeFZ** [comment]
Should be fixed now as the royal regimen menu appearing is based on the current drill mission id
