### ISSUE TITLE
Implement chapter 10 non-skip reward

### ISSUE THREAD

**Issue by SapiensAnatis** [SapiensAnatis/Dawnshard#787]
**Context**
In the original game, if you reached chapter 10 without using the campaign skip option, you were granted the following rewards:

- 69990 player EXP (level 1 -> 60)
- 350 Hustle Hammers
- Enough materials to upgrade the facilities upgraded by campaign skip

**The feature request**
This reward should be implemented on Dawnshard. A savefile update should be implemented to send these rewards to the gift box of players who have already passed the trigger for the reward. It is fine if this ends up granting it to players who have used campaign skip in the window since #525 was implemented. We should ensure that it is not rewarded to players who campaign skip after it is implemented, though.

**Comment by jaredstrong89** [comment]
I'm on it 🙂

**Comment by SapiensAnatis** [comment]
Closed by #788
